from kmk.keys import KC, make_key # type: ignore
# keycode abbreviations
# mods
LSFT = KC.LSFT
RSFT = KC.RSFT
LCMD = KC.LCMD
RCMD = KC.RCMD
LALT = KC.LALT
RALT = KC.RALT
LCTL = KC.LCTL
RCTL = KC.RCTL
# misc
ENTR = KC.ENT
SPAC = KC.SPACE
COMM = KC.COMMA
SEMI = KC.SCOLON
SLAS = KC.SLASH
PERI = KC.DOT
BSPC = KC.BSPC
DELE = KC.DEL
CAPS = KC.CAPS
ESCP = KC.ESCAPE
NONE = KC.NO
# numbers
NUM1 = KC.N1
NUM2 = KC.N2
NUM3 = KC.N3
NUM4 = KC.N4
NUM5 = KC.N5
NUM6 = KC.N6
NUM7 = KC.N7
NUM8 = KC.N8
NUM9 = KC.N9
NUM0 = KC.N0
# symbols
BANG = KC.EXLM
ROBA = KC.AT
HASH = KC.HASH
BUCK = KC.DLR
PERC = KC.PERC
CIRC = KC.CIRC
AMPR = KC.AMPR
STAR = KC.ASTR
# navigation
ARUP = KC.UP
ARLF = KC.LEFT
ARRT = KC.RIGHT
ARDN = KC.DOWN
# function
FN01 = KC.F1
FN02 = KC.F2
FN03 = KC.F3
FN04 = KC.F4
FN05 = KC.F5
FN06 = KC.F6
FN07 = KC.F7
FN08 = KC.F8
FN09 = KC.F9
FN10 = KC.F10
FN11 = KC.F11
FN12 = KC.F12